import streamlit as st
import joblib
import pandas as pd

# ---------------------------------------------------------------------------
# Page configuration
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="Late Delivery Risk Predictor",
    page_icon="🚚",
    layout="centered"
)

# ---------------------------------------------------------------------------
# Load kNN model artifacts
# These files must be present in the GitHub repository under a "model/" folder:
#   - model/knn_classifier_optimum.pkl
#   - model/scaler_3.pkl
#   - model/onehot_encoder_3.pkl
# ---------------------------------------------------------------------------
@st.cache_resource
def load_models():
    knn_model      = joblib.load("./model/knn_classifier_optimum.pkl")
    scaler         = joblib.load("./model/scaler_3.pkl")
    onehot_encoder = joblib.load("./model/onehot_encoder_3.pkl")
    return knn_model, scaler, onehot_encoder

knn_classifier_optimum, knn_scaler, knn_onehot_encoder = load_models()

SHIPPING_MODES = ["First Class", "Same Day", "Second Class", "Standard Class"]

# ---------------------------------------------------------------------------
# Page header
# ---------------------------------------------------------------------------
st.title("🚚 Late Delivery Risk Predictor")
st.write(
    "Predict whether an order is at risk of **late delivery** using an "
    "optimised **k-Nearest Neighbours (kNN) classifier**. "
    "Fill in the order details below and click **Predict**."
)
st.divider()

# ---------------------------------------------------------------------------
# Input form
# ---------------------------------------------------------------------------
with st.form("prediction_form"):
    st.subheader("📦 Order Details")

    col1, col2 = st.columns(2)

    with col1:
        days_shipping_real = st.number_input(
            "Days for Shipping (Real)",
            min_value=0, step=1, value=3,
            help="Actual number of days taken to ship the order."
        )
        days_shipment_scheduled = st.number_input(
            "Days for Shipment (Scheduled)",
            min_value=0, step=1, value=4,
            help="Originally scheduled number of shipping days."
        )
        order_item_quantity = st.number_input(
            "Order Item Quantity",
            min_value=1, step=1, value=1,
            help="Number of units ordered."
        )

    with col2:
        sales = st.number_input(
            "Sales (USD)",
            min_value=0.0, step=0.01, value=250.00,
            help="Total sales value of the order."
        )
        order_profit_per_order = st.number_input(
            "Order Profit Per Order (USD)",
            min_value=None, step=0.01, value=64.17,
            help="Profit generated by this order. Can be negative."
        )
        shipping_mode = st.selectbox(
            "Shipping Mode",
            options=SHIPPING_MODES,
            index=2,                          # Default: "Second Class"
            help="Shipping method selected for the order."
        )

    submitted = st.form_submit_button("Predict", use_container_width=True, type="primary")

# ---------------------------------------------------------------------------
# Prediction
# ---------------------------------------------------------------------------
if submitted:
    # Build a single-row DataFrame matching the training feature schema
    new_data = pd.DataFrame([{
        "Days for shipping (real)":      days_shipping_real,
        "Days for shipment (scheduled)": days_shipment_scheduled,
        "Order Item Quantity":           order_item_quantity,
        "Sales":                         sales,
        "Order Profit Per Order":        order_profit_per_order,
        "Shipping Mode":                 shipping_mode
    }])

    # One-hot encode "Shipping Mode" using the saved encoder (drop='first')
    encoded = knn_onehot_encoder.transform(new_data[["Shipping Mode"]])
    encoded_df = pd.DataFrame(
        encoded,
        columns=knn_onehot_encoder.get_feature_names_out(["Shipping Mode"]),
        index=new_data.index
    )

    # Replace the raw categorical column with the encoded columns
    new_data = pd.concat(
        [new_data.drop("Shipping Mode", axis=1), encoded_df],
        axis=1
    )

    # Scale using the saved StandardScaler
    new_data_scaled = knn_scaler.transform(new_data)

    # Predict class and probabilities
    prediction    = int(knn_classifier_optimum.predict(new_data_scaled)[0])
    probabilities = knn_classifier_optimum.predict_proba(new_data_scaled)[0]
    prob_on_time  = round(float(probabilities[0]) * 100, 1)
    prob_late     = round(float(probabilities[1]) * 100, 1)

    # ---------------------------------------------------------------------------
    # Display results
    # ---------------------------------------------------------------------------
    st.divider()
    st.subheader("📊 Prediction Result")

    if prediction == 1:
        st.error("### 🔴 Late Delivery Risk Detected")
    else:
        st.success("### 🟢 On Time — No Late Delivery Risk")

    col_a, col_b = st.columns(2)
    col_a.metric("On Time (Class 0)",       f"{prob_on_time}%")
    col_b.metric("Late Delivery (Class 1)", f"{prob_late}%")

    with st.expander("ℹ️ How to interpret this result"):
        st.markdown(
            """
            | Class | Meaning |
            |---|---|
            | **0 – On Time** | The order is predicted to arrive on or before the scheduled date |
            | **1 – Late Delivery** | The order is predicted to arrive after the scheduled date |

            The percentages above show the model's confidence for each class.
            A higher percentage means the model is more certain of that outcome.
            """
        )

# ---------------------------------------------------------------------------
# Reference table (always visible)
# ---------------------------------------------------------------------------
st.divider()
with st.expander("📋 Input Field Reference"):
    st.markdown(
        """
        | Field | Description |
        |---|---|
        | Days for Shipping (Real) | How many days it actually took to ship |
        | Days for Shipment (Scheduled) | How many days were originally planned |
        | Order Item Quantity | Number of items in the order |
        | Sales (USD) | Total monetary value of the order |
        | Order Profit Per Order (USD) | Profit earned from the order (can be negative) |
        | Shipping Mode | First Class · Same Day · Second Class · Standard Class |
        """
    )